[workspace]
authors = ["Ogarit <tiagomarquesdados@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "API_Visialization"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.0,<3.15"
requests = ">=2.32.5,<3"
